/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "nikita.check" instead.
 */

#include <check.h>

#include "../headers/s21_string.h"

START_TEST(memchr1)
{
    char str24[100] = "";
    char str25[100] = "string";
    char str26[100] = "Atring";
    char str27[100] = "StringA";
    char str28[100] = "Str3";
    char str30 = "1-2-3-4-5";
    ck_assert_str_eq(s21_memchr(str25, '\0', 7), memchr(str25, '\0', 7));
    ck_assert_str_eq(s21_memchr(str26, 'A', 6), memchr(str26, 'A', 6));
    ck_assert_str_eq(s21_memchr(str27, 'A', 7), memchr(str27, 'A', 7));
    ck_assert_str_eq(s21_memchr(str28, '3', 5), memchr(str28, '3', 5));
    ck_assert_str_eq(s21_memchr(str30, '-', 9), memchr(str30, '-', 9));

}
END_TEST

START_TEST(memcmp1)
{
    char str31[100] = "aboba";
    char str32[100] = "aboba";
    char str33[100] = "Aboba";
    char str34[100] = "1";
    char str35[100] = "1";
    char str36[100] = "1234";
    char str37[100] = "13";
    char str38[100] = "111111111111111111112312312312312312434524563567adsfe 4rafa ewfseASDASD";
    char str39[100] = "111111111111111111112312312312312312434524563567adsfe 4rafa ewfseASDASd";
    ck_assert_int_eq(s21_memcmp(str31, str32, 0), memcmp(str31, str32, 0));
    ck_assert_int_eq(s21_memcmp(str31, str32, 3), memcmp(str31, str32, 3));
    ck_assert_int_eq(s21_memcmp(str31, str33, 1), memcmp(str31, str33, 1));
    ck_assert_int_eq(s21_memcmp(str34, str35, 0), memcmp(str34, str35, 0));
    ck_assert_int_eq(s21_memcmp(str34, str36, 1), memcmp(str34, str36, 1));
    ck_assert_int_eq(s21_memcmp(str36, str36, 2), memcmp(str36, str36, 2));
    ck_assert_int_eq(s21_memcmp(str36, str37, 2), memcmp(str36, str37, 2));
    ck_assert_int_eq(s21_memcmp(str38, str38, 71), memcmp(str38, str38, 71));
    ck_assert_int_eq(s21_memcmp(str38, str39, 71), memcmp(str38, str39, 71));

}
END_TEST

START_TEST(memcpy1)
{
    char str40[100] = "i hate memcmp";
    char str41[100] = "aboba";
    char str42[100] = "";
    char str43[100] = "I hate memcmp";
    char str44[100] = "123";
    char str45[100] = "aposkd AOSIjFasodijpaoisdjf poisdjfg";
    char dest[100] = {0};
    ck_assert_str_eq(s21_memcpy(str40, dest, 12), memcpy(str40, dest, 12));
    ck_assert_str_eq(s21_memcpy(str41, dest, 0), memcpy(str41, dest, 0));
    ck_assert_str_eq(s21_memcpy(str42, dest, 0), memcpy(str42, dest, 0));
    ck_assert_str_eq(s21_memcpy(str43, dest, 1), memcpy(str43, dest, 1));
    ck_assert_str_eq(s21_memcpy(str44, dest, 3), memcpy(str44, dest, 2));
    ck_assert_str_eq(s21_memcpy(str45, dest, 28), memcpy(str45, dest, 28));

}
END_TEST

START_TEST(memmove1)
{
    char str46[100] = "i love memcmp";
    char str47[100] = "aboba";
    char str48[100] = "";
    char str49[100] = "I love memcmp";
    char str50[100] = "123";
    char str51[100] = "aposkd AOSIjFasodijpaoisdjf poisdjfg";
    char dest[100] = "0000000000000000";
    ck_assert_str_eq(s21_memcpy(str47, dest, 0), memcpy(str47, dest, 0));
    ck_assert_str_eq(s21_memcpy(str48, dest, 0), memcpy(str48, dest, 0));
    ck_assert_str_eq(s21_memcpy(str49, dest, 1), memcpy(str49, dest, 1));
    ck_assert_str_eq(s21_memcpy(str50, dest, 3), memcpy(str50, dest, 2));
    ck_assert_str_eq(s21_memcpy(str51, dest, 28), memcpy(str51, dest, 28));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, memchr1);
    tcase_add_test(tc1_1, memcmp1);
    tcase_add_test(tc1_1, memcpy1);
    tcase_add_test(tc1_1, memmove1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
